"""
FinGuard AI - Anomaly Detector
------------------------------
Isolation Forest based anomaly detection utilities.
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

MODELS_DIR = PROJECT_ROOT / "Models"

ANOMALY_MODEL_DIR = MODELS_DIR / "anomaly_model"

ANOMALY_MODEL_PATH = ANOMALY_MODEL_DIR / "isolation_forest.pkl"

# Actual artifact generated by Notebook 08.
ANOMALY_RESULTS_PATH = (
    PROJECT_ROOT
    / "Reports"
    / "Model_Evaluation"
    / "anomaly_detection_results.csv"
)


# ============================================================
# MODEL LOADING
# ============================================================

def load_anomaly_model():
    """
    Load the trained Isolation Forest model.
    """

    if not ANOMALY_MODEL_PATH.exists():
        raise FileNotFoundError(
            f"Isolation Forest model not found: {ANOMALY_MODEL_PATH}"
        )

    return joblib.load(ANOMALY_MODEL_PATH)


# ============================================================
# ANOMALY PREDICTION
# ============================================================

def predict_anomalies(model, X):
    """
    Predict anomalies using Isolation Forest.

    Returns
    -------
    numpy.ndarray
        1  = normal
        -1 = anomaly
    """

    if X is None:
        raise ValueError("Input data cannot be None.")

    return model.predict(X)


def anomaly_scores(model, X):
    """
    Generate Isolation Forest anomaly scores.
    """

    if not hasattr(model, "decision_function"):
        raise AttributeError(
            "The anomaly model does not support decision_function()."
        )

    return model.decision_function(X)


# ============================================================
# BATCH ANOMALY DETECTION
# ============================================================

def detect_anomalies(model, X):
    """
    Detect anomalies and return a structured DataFrame.
    """

    predictions = predict_anomalies(model, X)
    scores = anomaly_scores(model, X)

    results = pd.DataFrame({
        "anomaly_prediction": predictions,
        "anomaly_score": scores
    })

    results["is_anomaly"] = (
        results["anomaly_prediction"] == -1
    ).astype(int)

    results["anomaly_status"] = np.where(
        results["is_anomaly"] == 1,
        "Anomaly",
        "Normal"
    )

    return results


# ============================================================
# SINGLE TRANSACTION
# ============================================================

def analyze_transaction(model, transaction):
    """
    Analyze a single transaction for anomalous behaviour.
    """

    if isinstance(transaction, dict):
        transaction = pd.DataFrame([transaction])

    if not isinstance(transaction, pd.DataFrame):
        raise TypeError(
            "transaction must be a dictionary or pandas DataFrame."
        )

    result = detect_anomalies(model, transaction)

    row = result.iloc[0]

    return {
        "anomaly_prediction": int(row["anomaly_prediction"]),
        "anomaly_score": float(row["anomaly_score"]),
        "is_anomaly": int(row["is_anomaly"]),
        "anomaly_status": row["anomaly_status"]
    }


# ============================================================
# ANOMALY STATISTICS
# ============================================================

def get_anomaly_statistics(results):
    """
    Calculate summary statistics from anomaly results.
    """

    if not isinstance(results, pd.DataFrame):
        raise TypeError(
            "results must be a pandas DataFrame."
        )

    if "is_anomaly" not in results.columns:
        raise ValueError(
            "Results must contain 'is_anomaly' column."
        )

    total_transactions = len(results)
    anomaly_count = int(results["is_anomaly"].sum())

    anomaly_rate = (
        anomaly_count / total_transactions * 100
        if total_transactions > 0
        else 0.0
    )

    return {
        "total_transactions": total_transactions,
        "detected_anomalies": anomaly_count,
        "normal_transactions": (
            total_transactions - anomaly_count
        ),
        "anomaly_rate": anomaly_rate
    }