"""
FinGuard AI - Fraud Model Predictor
------------------------------------
Loads the final trained fraud model and provides
reusable prediction utilities for the application layer.
"""

from pathlib import Path
import joblib
import numpy as np
import pandas as pd


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

MODELS_DIR = PROJECT_ROOT / "Models"

# Final model artifacts generated by the modeling notebooks.
OPTIMIZED_MODEL_PATH = MODELS_DIR / "optimized_fraud_model.joblib"
BEST_MODEL_PATH = MODELS_DIR / "best_fraud_model.joblib"

# Metadata generated during final model/prediction stage.
FINAL_METADATA_PATH = MODELS_DIR / "final_model_metadata.joblib"


# ============================================================
# MODEL LOADING
# ============================================================

def load_fraud_model():
    """
    Load the final fraud detection model.

    Priority:
        1. optimized_fraud_model.joblib
        2. best_fraud_model.joblib
    """

    if OPTIMIZED_MODEL_PATH.exists():
        return joblib.load(OPTIMIZED_MODEL_PATH)

    if BEST_MODEL_PATH.exists():
        return joblib.load(BEST_MODEL_PATH)

    raise FileNotFoundError(
        "No final fraud model found in the Models directory."
    )


def load_model_metadata():
    """
    Load final model metadata if available.
    """

    if not FINAL_METADATA_PATH.exists():
        return {}

    metadata = joblib.load(FINAL_METADATA_PATH)

    if isinstance(metadata, dict):
        return metadata

    return {}


# ============================================================
# PREDICTION
# ============================================================

def predict_probability(model, X):
    """
    Generate fraud probabilities.
    """

    if not hasattr(model, "predict_proba"):
        raise AttributeError(
            "The loaded model does not support predict_proba()."
        )

    probabilities = model.predict_proba(X)

    # Binary classification → probability of class 1
    if probabilities.shape[1] >= 2:
        return probabilities[:, 1]

    return probabilities[:, 0]


def predict_fraud(model, X, threshold=0.50):
    """
    Generate fraud predictions using the supplied threshold.
    """

    probabilities = predict_probability(model, X)

    predictions = (probabilities >= threshold).astype(int)

    return predictions, probabilities


# ============================================================
# SINGLE TRANSACTION PREDICTION
# ============================================================

def predict_transaction(model, transaction, threshold=0.50):
    """
    Predict a single transaction.

    Parameters
    ----------
    model : trained classifier
    transaction : pandas DataFrame or dictionary
    threshold : fraud decision threshold

    Returns
    -------
    dict
        Prediction result containing fraud probability,
        prediction and risk score.
    """

    if isinstance(transaction, dict):
        transaction = pd.DataFrame([transaction])

    if not isinstance(transaction, pd.DataFrame):
        raise TypeError(
            "transaction must be a dictionary or pandas DataFrame."
        )

    predictions, probabilities = predict_fraud(
        model,
        transaction,
        threshold=threshold
    )

    probability = float(probabilities[0])
    prediction = int(predictions[0])

    return {
        "prediction": prediction,
        "fraud_probability": probability,
        "fraud_percentage": probability * 100,
        "risk_score": probability * 100,
        "result": (
            "Fraudulent Transaction"
            if prediction == 1
            else "Legitimate Transaction"
        )
    }


# ============================================================
# BATCH PREDICTION
# ============================================================

def predict_batch(model, X, threshold=0.50):
    """
    Generate predictions for multiple transactions.
    """

    predictions, probabilities = predict_fraud(
        model,
        X,
        threshold=threshold
    )

    results = pd.DataFrame({
        "fraud_probability": probabilities,
        "risk_score": probabilities * 100,
        "prediction": predictions
    })

    results["result"] = np.where(
        results["prediction"] == 1,
        "Fraudulent Transaction",
        "Legitimate Transaction"
    )

    return results


# ============================================================
# MODEL INFORMATION
# ============================================================

def get_model_info():
    """
    Return information about the loaded fraud model.
    """

    model = load_fraud_model()
    metadata = load_model_metadata()

    return {
        "model_type": type(model).__name__,
        "model_path": str(
            OPTIMIZED_MODEL_PATH
            if OPTIMIZED_MODEL_PATH.exists()
            else BEST_MODEL_PATH
        ),
        "metadata": metadata
    }